---
name: ⛑️ Support Request
description: Find out how to get answers and/or submit a support request.
labels: [question]
body:
  - type: textarea
    id: support
    attributes:
      label: ⛑️ Support Request
      description: Add your support request here. Detail exactly what you need help with.
    validations:
      required: true
